name: Simulator Sanity Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sim-startup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
      - name: Verify simulator starts up
        run: |
          ./scripts/verify-simulator-starts.sh
